DOCUMENT_EXTENSIONS = (".pdf", ".doc", ".docx", ".xls", ".xlsx", ".ppt", ".pptx")
SKIP_EXTENSIONS = (
    ".css",
    ".gif",
    ".ico",
    ".jpg",
    ".jpeg",
    ".js",
    ".png",
    ".svg",
    ".webp",
    ".zip",
)
COMMON_PATHS = (
    "/about-us/board-papers/",
    "/about-us/board-meetings/",
    "/about-us/trust-board/",
    "/about-us/trust-board/board-papers/",
    "/about-us/trust-board/board-meetings/",
    "/about-us/our-board/",
    "/about-us/board/",
    "/about-us/publications/",
    "/about-us/governance/",
    "/about-us/governance/board-papers/",
    "/about-us/accountability/",
    "/about-us/corporate-documents/",
    "/about-us/corporate-documents/trust-board-papers/",
    "/about-us/corporate-governance/",
    "/about-us/board-of-directors/",
    "/about-us/board-of-directors/board-papers/",
    "/about-us/freedom-of-information/",
    "/board-papers/",
    "/board-papers-and-minutes/",
    "/board-meetings/",
    "/trust-board/",
    "/trust-board/board-papers/",
    "/our-trust/board-of-directors/",
    "/our-board/",
    "/corporate-governance/",
    "/corporate-documents/",
    "/key-information/board-papers/",
    "/about/board/",
    "/about/governance/",
    "/about/trust-board/",
    "/transparency/",
    "/get-involved/board/",
    "/meetings/",
    "/publications/",
    "/governance/",
    "/governance/board-papers/",
    "/board-and-governance/",
    "/our-organisation/board/",
    "/our-organisation/governance/",
    "/key-documents/",
    "/strategy/",
    "/digital/",
)

# URL path fragments that indicate a navigation/index page worth following even
# if no board-paper keywords appear in its link text. Prevents intermediate
# pages like /corporate-documents/ from being silently dropped.
NAV_PATH_FRAGMENTS = (
    "corporate",
    "governance",
    "publications",
    "accountability",
    "transparency",
    "about-us",
    "about",
    "our-trust",
    "documents",
    "resources",
    "key-information",
    "our-information",
    "information",
    "organisation",
    "freedom-of-information",
)
MONTHS = {
    "jan": 1,
    "january": 1,
    "feb": 2,
    "february": 2,
    "mar": 3,
    "march": 3,
    "apr": 4,
    "april": 4,
    "may": 5,
    "jun": 6,
    "june": 6,
    "jul": 7,
    "july": 7,
    "aug": 8,
    "august": 8,
    "sep": 9,
    "sept": 9,
    "september": 9,
    "oct": 10,
    "october": 10,
    "nov": 11,
    "november": 11,
    "dec": 12,
    "december": 12,
}
REPORT_TYPES = {
    "board": {
        "folder": "board-papers",
        "page_terms": (
            "board papers",
            "board meetings",
            "board meeting",
            "trust board",
            "board of directors",
            "board packs",
            "board pack",
            "public board",
            "meeting papers",
        ),
        "file_terms": (
            "board paper",
            "board papers",
            "board pack",
            "meeting pack",
            "board agenda",
            "public board",
            "trust board",
            "board of directors",
        ),
        "required_any": ("board",),
        "bonus": 100,
    },
    "supplementary": {
        "folder": "supplementary-material",
        "page_terms": (
            "board papers",
            "board meetings",
            "supplementary",
            "supporting papers",
            "appendix",
            "appendices",
            "enclosure",
        ),
        "file_terms": (
            "supplementary",
            "supporting paper",
            "supporting papers",
            "appendix",
            "appendices",
            "enclosure",
            "additional papers",
            "part 2",
        ),
        "required_any": (),
        "bonus": 70,
    },
    "strategy": {
        "folder": "strategic-reporting",
        "page_terms": (
            "strategy",
            "strategic",
            "annual plan",
            "operational plan",
            "forward plan",
            "corporate plan",
        ),
        "file_terms": (
            "strategy",
            "strategic",
            "annual plan",
            "operational plan",
            "forward plan",
            "corporate plan",
            "integrated performance",
            "quality account",
            "annual report",
        ),
        "required_any": (),
        "bonus": 75,
    },
    "digital_strategy": {
        "folder": "digital-strategy",
        "page_terms": (
            "digital strategy",
            "digital",
            "data strategy",
            "technology",
            "informatics",
        ),
        "file_terms": (
            "digital strategy",
            "data strategy",
            "technology strategy",
            "informatics strategy",
            "digital plan",
            "digital roadmap",
            "digital transformation strategy",
            "electronic patient record",
        ),
        "required_any": (),
        "bonus": 85,
    },
}
